const baseUrl = 'https://www.wakfu.com/en/mmorpg/encyclopedia/classes';
const urlParams = '?_pjax=.ak-spells-panel';
const classEncyclopediaBreakdown = [
  {
    classUrlPath: '/1-feca',
    className: 'Feca',
    classId: 1,
    spells: [
      { spellId: 6982, spellName: 'Immunity', spellUrlPath: '/6982-immunity' },
      { spellId: 6983, spellName: 'Truce', spellUrlPath: '/6983-truce' },
      { spellId: 6984, spellName: 'Pacification', spellUrlPath: '/6984-pacification' },
      { spellId: 6985, spellName: 'Provocation', spellUrlPath: '/6985-provocation' },
      { spellId: 6986, spellName: 'Aegis', spellUrlPath: '/6986-aegis' },
      { spellId: 6987, spellName: 'Magnetism', spellUrlPath: '/6987-magnetism' },
      { spellId: 6997, spellName: 'Rocky Skin', spellUrlPath: '/6997-rocky-skin' },
      { spellId: 7004, spellName: 'Wakfu Comprehension', spellUrlPath: '/7004-wakfu-comprehension' },
      { spellId: 7003, spellName: 'Spiny Carapace', spellUrlPath: '/7003-spiny-carapace' },
      { spellId: 7002, spellName: 'Elemental Shields', spellUrlPath: '/7002-elemental-shields' },
      { spellId: 7001, spellName: 'Field Experience', spellUrlPath: '/7001-field-experience' },
      { spellId: 7000, spellName: 'Shepherd', spellUrlPath: '/7000-shepherd' },
      { spellId: 6999, spellName: 'Persistent Glyphs', spellUrlPath: '/6999-persistent-glyphs' },
      { spellId: 6998, spellName: 'Eye for Eye', spellUrlPath: '/6998-eye-eye' },
      { spellId: 6994, spellName: 'Map Mastery', spellUrlPath: '/6994-map-mastery' },
      { spellId: 6996, spellName: 'Combat Armor', spellUrlPath: '/6996-combat-armor' },
      { spellId: 6995, spellName: 'The Best Defense Is an Attack', spellUrlPath: '/6995-best-defense-attack' },
      { spellId: 6988, spellName: 'Increased Glyph', spellUrlPath: '/6988-increased-glyph' },
      { spellId: 6993, spellName: 'Pacifist Pact', spellUrlPath: '/6993-pacifist-pact' },
      { spellId: 6992, spellName: 'If You Want Peace, Prepare for War', spellUrlPath: '/6992-if-you-want-peace-prepare' },
      { spellId: 6991, spellName: 'Master of Shields', spellUrlPath: '/6991-master-shields' },
      { spellId: 6990, spellName: 'One for All', spellUrlPath: '/6990-one-all' },
      { spellId: 6989, spellName: 'Line', spellUrlPath: '/6989-line' },
      { spellId: 7005, spellName: 'Herd Protector', spellUrlPath: '/7005-herd-protector' },
    ],
  },
  {
    classUrlPath: '/2-osamodas',
    className: 'Osamodas',
    classId: 2,
    spells: [
      { spellId: 7322, spellName: 'Last Breath', spellUrlPath: '/7322-last-breath' },
      { spellId: 7323, spellName: 'Motivating Shot', spellUrlPath: '/7323-motivating-shot' },
      { spellId: 7324, spellName: 'Velocity', spellUrlPath: '/7324-velocity' },
      { spellId: 7325, spellName: 'Weakening Cry', spellUrlPath: '/7325-weakening-cry' },
      { spellId: 7326, spellName: 'Relay', spellUrlPath: '/7326-relay' },
      { spellId: 7327, spellName: 'Animal Link', spellUrlPath: '/7327-animal-link' },
      { spellId: 7337, spellName: 'Symbiosa', spellUrlPath: '/7337-symbiosa' },
      { spellId: 7343, spellName: 'The Art of Taming', spellUrlPath: '/7343-art-taming' },
      { spellId: 7342, spellName: 'Animal Devotion', spellUrlPath: '/7342-animal-devotion' },
      { spellId: 7341, spellName: 'Eastern Star', spellUrlPath: '/7341-eastern-star' },
      { spellId: 7340, spellName: 'Animal Sacrifice', spellUrlPath: '/7340-animal-sacrifice' },
      { spellId: 7339, spellName: 'South Star', spellUrlPath: '/7339-south-star' },
      { spellId: 7333, spellName: 'Dragonic Transcendence', spellUrlPath: '/7333-dragonic-transcendence' },
      { spellId: 7338, spellName: 'Dragonic Power', spellUrlPath: '/7338-dragonic-power' },
      { spellId: 7336, spellName: 'Animal Synergy', spellUrlPath: '/7336-animal-synergy' },
      { spellId: 7335, spellName: 'Taur Strength', spellUrlPath: '/7335-taur-strength' },
      { spellId: 7334, spellName: 'Phoenix Spirit', spellUrlPath: '/7334-phoenix-spirit' },
      { spellId: 7328, spellName: 'Boowolf Fury', spellUrlPath: '/7328-boowolf-fury' },
      { spellId: 7332, spellName: 'Solitary Summoner', spellUrlPath: '/7332-solitary-summoner' },
      { spellId: 7331, spellName: 'Summoning Warrior', spellUrlPath: '/7331-summoning-warrior' },
      { spellId: 7330, spellName: 'Crobak Vision', spellUrlPath: '/7330-crobak-vision' },
      { spellId: 7329, spellName: 'Animal Gift', spellUrlPath: '/7329-animal-gift' },
      { spellId: 7344, spellName: 'Animal Sharing', spellUrlPath: '/7344-animal-sharing' },
    ],
  },
  {
    classUrlPath: '/3-enutrof',
    className: 'Enutrof',
    classId: 3,
    spells: [
      { spellId: 6324, spellName: 'Excavation', spellUrlPath: '/6324-excavation' },
      { spellId: 2027, spellName: 'Phone a Frhend', spellUrlPath: '/2027-phone-frhend' },
      { spellId: 6405, spellName: 'Debt', spellUrlPath: '/6405-debt' },
      { spellId: 6337, spellName: 'Clumsiness', spellUrlPath: '/6337-clumsiness' },
      { spellId: 2064, spellName: 'Prime of Life', spellUrlPath: '/2064-prime-life' },
      { spellId: 2026, spellName: 'Seismic Wealth', spellUrlPath: '/2026-seismic-wealth' },
      { spellId: 2028, spellName: 'Treasure Tracker', spellUrlPath: '/2028-treasure-tracker' },
      { spellId: 2009, spellName: 'Advanced Geology', spellUrlPath: '/2009-advanced-geology' },
      { spellId: 2057, spellName: 'Not Dead Yet', spellUrlPath: '/2057-not-dead-yet' },
      { spellId: 5076, spellName: 'Trade Secrets', spellUrlPath: '/5076-trade-secrets' },
      { spellId: 2039, spellName: 'Enutrofs Blessing', spellUrlPath: '/2039-enutrof-blessing' },
      { spellId: 5059, spellName: 'Enutrof Force of Will', spellUrlPath: '/5059-enutrof-force-will' },
      { spellId: 5075, spellName: 'Drhellzertank', spellUrlPath: '/5075-drhellzertank' },
      { spellId: 2040, spellName: 'Faking It', spellUrlPath: '/2040-faking' },
      { spellId: 6326, spellName: 'Credit Interest', spellUrlPath: '/6326-credit-interest' },
      { spellId: 5071, spellName: 'Greed', spellUrlPath: '/5071-greed' },
    ],
  },
  {
    classUrlPath: '/4-sram',
    className: 'Sram',
    classId: 4,
    spells: [
      { spellId: 4604, spellName: 'Invisibility', spellUrlPath: '/4604-invisibility' },
      { spellId: 4603, spellName: 'Double', spellUrlPath: '/4603-double' },
      { spellId: 4597, spellName: 'Shadow Trap', spellUrlPath: '/4597-shadow-trap' },
      { spellId: 4601, spellName: 'Scram', spellUrlPath: '/4601-scram' },
      { spellId: 6850, spellName: 'Assassination', spellUrlPath: '/6850-assassination' },
      { spellId: 4602, spellName: 'Stabber', spellUrlPath: '/4602-stabber' },
      { spellId: 4608, spellName: 'Murderer', spellUrlPath: '/4608-murderer' },
      { spellId: 5123, spellName: 'Bloody Blade', spellUrlPath: '/5123-bloody-blade' },
      { spellId: 4606, spellName: 'Brutal Assault', spellUrlPath: '/4606-brutal-assault' },
      { spellId: 4607, spellName: 'Shadow Master', spellUrlPath: '/4607-shadow-master' },
      { spellId: 4609, spellName: 'Trap Master', spellUrlPath: '/4609-trap-master' },
      { spellId: 5089, spellName: 'Crazy Scheme', spellUrlPath: '/5089-crazy-scheme' },
      { spellId: 5122, spellName: 'Ambush', spellUrlPath: '/5122-ambush' },
      { spellId: 5124, spellName: 'Fraud', spellUrlPath: '/5124-fraud' },
      { spellId: 5126, spellName: 'Dupery', spellUrlPath: '/5126-dupery' },
      { spellId: 4610, spellName: 'Sram to the Bone', spellUrlPath: '/4610-sram-bone' },
    ],
  },
  {
    classUrlPath: '/5-xelor',
    className: 'Xelor',
    classId: 5,
    spells: [
      { spellId: 2839, spellName: 'Devotion', spellUrlPath: '/2839-devotion' },
      { spellId: 776, spellName: 'Against the Clock', spellUrlPath: '/776-against-clock' },
      { spellId: 777, spellName: 'Sinistro', spellUrlPath: '/777-sinistro' },
      { spellId: 766, spellName: 'Cog', spellUrlPath: '/766-cog' },
      { spellId: 757, spellName: 'Premonition', spellUrlPath: '/757-premonition' },
      { spellId: 5344, spellName: 'Regulator', spellUrlPath: '/5344-regulator' },
      { spellId: 7186, spellName: 'Knowledge of the Past', spellUrlPath: '/7186-knowledge-past' },
      { spellId: 7195, spellName: 'Shriveling', spellUrlPath: '/7195-shriveling' },
      { spellId: 7193, spellName: 'Combat Mage', spellUrlPath: '/7193-combat-mage' },
      { spellId: 7192, spellName: 'Momentary Permutation', spellUrlPath: '/7192-momentary-permutation' },
      { spellId: 7191, spellName: 'Specialized Mechanisms', spellUrlPath: '/7191-specialized-mechanisms' },
      { spellId: 7190, spellName: 'Remanence', spellUrlPath: '/7190-remanence' },
      { spellId: 7189, spellName: 'Slowdown of Time', spellUrlPath: '/7189-slowdown-time' },
      { spellId: 7188, spellName: 'Dark Dimension', spellUrlPath: '/7188-dark-dimension' },
      { spellId: 7187, spellName: 'Violent Omens', spellUrlPath: '/7187-violent-omens' },
      { spellId: 785, spellName: 'Course of Time', spellUrlPath: '/785-course-time' },
      { spellId: 7185, spellName: 'Deja Vu', spellUrlPath: '/7185-vu' },
      { spellId: 7184, spellName: 'Counterclockwise', spellUrlPath: '/7184-counterclockwise' },
      { spellId: 758, spellName: 'Dial Master', spellUrlPath: '/758-dial-master' },
      { spellId: 756, spellName: 'Memory', spellUrlPath: '/756-memory' },
      { spellId: 761, spellName: 'Clockmaking', spellUrlPath: '/761-clockmaking' },
      { spellId: 764, spellName: 'Tock Tick', spellUrlPath: '/764-tock-tick' },
      { spellId: 5353, spellName: 'Tick Tock', spellUrlPath: '/5353-tick-tock' },
      { spellId: 5351, spellName: 'Portent', spellUrlPath: '/5351-portent' },
      { spellId: 5352, spellName: 'Timeliness', spellUrlPath: '/5352-timeliness' },
      { spellId: 7196, spellName: 'Assimilation', spellUrlPath: '/7196-assimilation' },
    ],
  },
  {
    classUrlPath: '/6-ecaflip',
    className: 'Ecaflip',
    classId: 6,
    spells: [
      { spellId: 2060, spellName: 'Double or Quits', spellUrlPath: '/2060-double-quits' },
      { spellId: 2075, spellName: 'Topkaj', spellUrlPath: '/2075-topkaj' },
      { spellId: 2061, spellName: 'Felintuition', spellUrlPath: '/2061-felintuition' },
      { spellId: 2078, spellName: 'Life Token', spellUrlPath: '/2078-life-token' },
      { spellId: 2079, spellName: 'Spell Strike', spellUrlPath: '/2079-spell-strike' },
      { spellId: 7225, spellName: 'Clubs', spellUrlPath: '/7225-clubs' },
      { spellId: 7955, spellName: 'Feline Tarot', spellUrlPath: '/7955-feline-tarot' },
      { spellId: 7999, spellName: 'Lucky Seven', spellUrlPath: '/7999-lucky-seven' },
      { spellId: 8001, spellName: 'Lucky Cards', spellUrlPath: '/8001-lucky-cards' },
      { spellId: 7961, spellName: 'Trump Cards', spellUrlPath: '/7961-trump-cards' },
      { spellId: 7960, spellName: 'Blackjack', spellUrlPath: '/7960-blackjack' },
      { spellId: 7959, spellName: 'Graceful Feline', spellUrlPath: '/7959-graceful-feline' },
      { spellId: 7958, spellName: 'Generous Dice', spellUrlPath: '/7958-generous-dice' },
      { spellId: 7957, spellName: 'Heads I win', spellUrlPath: '/7957-heads-i-win' },
      { spellId: 7956, spellName: 'Fortune Favors the Bold', spellUrlPath: '/7956-fortune-favors-bold' },
      { spellId: 5249, spellName: 'Feline Impact', spellUrlPath: '/5249-feline-impact' },
      { spellId: 7954, spellName: 'Healing Luck', spellUrlPath: '/7954-healing-luck' },
      { spellId: 5251, spellName: 'Cheat', spellUrlPath: '/5251-cheat' },
      { spellId: 2068, spellName: 'Misadventure', spellUrlPath: '/2068-misadventure' },
      { spellId: 5250, spellName: 'Ecaflips Fate', spellUrlPath: '/5250-ecaflip-fate' },
      { spellId: 5246, spellName: 'Prophetic Tarot', spellUrlPath: '/5246-prophetic-tarot' },
      { spellId: 2059, spellName: 'Lucky Tarot', spellUrlPath: '/2059-lucky-tarot' },
      { spellId: 2080, spellName: 'Misfortune', spellUrlPath: '/2080-misfortune' },
      { spellId: 2076, spellName: 'Winning Streak', spellUrlPath: '/2076-winning-streak' },
      { spellId: 2062, spellName: 'Fleassive', spellUrlPath: '/2062-fleassive' },
      { spellId: 8000, spellName: 'Universe', spellUrlPath: '/8000-universe' },
    ],
  },
  {
    classUrlPath: '/7-eniripsa',
    className: 'Eniripsa',
    classId: 7,
    spells: [
      { spellId: 782, spellName: 'Fountain of Youth', spellUrlPath: '/782-fountain-youth' },
      { spellId: 781, spellName: 'Bond of Friendship', spellUrlPath: '/781-bond-friendship' },
      { spellId: 627, spellName: 'Transcendence', spellUrlPath: '/627-transcendence' },
      { spellId: 1538, spellName: 'Ban', spellUrlPath: '/1538-ban' },
      { spellId: 7985, spellName: 'Life-Saving Fountain', spellUrlPath: '/7985-life-saving-fountain' },
      { spellId: 1535, spellName: 'Eniraser', spellUrlPath: '/1535-eniraser' },
      { spellId: 1536, spellName: 'Vital Climax', spellUrlPath: '/1536-vital-climax' },
      { spellId: 5451, spellName: 'Delay', spellUrlPath: '/5451-delay' },
      { spellId: 7998, spellName: 'Ambivalence', spellUrlPath: '/7998-ambivalence' },
      { spellId: 7997, spellName: 'Unnatural Paradox', spellUrlPath: '/7997-unnatural-paradox' },
      { spellId: 5453, spellName: 'All for Me', spellUrlPath: '/5453-all-me' },
      { spellId: 7996, spellName: 'Anbarul Mark', spellUrlPath: '/7996-anbarul-mark' },
      { spellId: 7995, spellName: 'Production Secret', spellUrlPath: '/7995-production-secret' },
      { spellId: 7994, spellName: 'Apprentice Alchemist', spellUrlPath: '/7994-apprentice-alchemist' },
      { spellId: 7993, spellName: 'Wind Elixir', spellUrlPath: '/7993-wind-elixir' },
      { spellId: 628, spellName: 'Doctor Without Borders', spellUrlPath: '/628-doctor-without-borders' },
      { spellId: 7992, spellName: 'Transgression', spellUrlPath: '/7992-transgression' },
      { spellId: 7991, spellName: 'Super Coney II', spellUrlPath: '/7991-super-coney-ii' },
      { spellId: 1415, spellName: 'Single Heal', spellUrlPath: '/1415-single-heal' },
      { spellId: 7990, spellName: 'Presence', spellUrlPath: '/7990-presence' },
      { spellId: 7987, spellName: 'Radiance', spellUrlPath: '/7987-radiance' },
      { spellId: 5463, spellName: 'Vampiripsa', spellUrlPath: '/5463-vampiripsa' },
      { spellId: 644, spellName: 'Precision Marking', spellUrlPath: '/644-precision-marking' },
      { spellId: 5454, spellName: 'Puncture', spellUrlPath: '/5454-puncture' },
      { spellId: 1537, spellName: 'Serial Marker', spellUrlPath: '/1537-serial-marker' },
      { spellId: 5455, spellName: 'Still Life', spellUrlPath: '/5455-still-life' },
    ],
  },
  {
    classUrlPath: '/8-iop',
    className: 'Iop',
    classId: 8,
    spells: [
      { spellId: 4790, spellName: 'Jump', spellUrlPath: '/4790-jump' },
      { spellId: 4791, spellName: 'Defensive Stance', spellUrlPath: '/4791-defensive-stance' },
      { spellId: 4793, spellName: 'Bravery Standard', spellUrlPath: '/4793-bravery-standard' },
      { spellId: 4792, spellName: 'Focus', spellUrlPath: '/4792-focus' },
      { spellId: 5130, spellName: 'Hour of Glory', spellUrlPath: '/5130-hour-glory' },
      { spellId: 4794, spellName: 'Increase', spellUrlPath: '/4794-increase' },
      { spellId: 4795, spellName: 'Virility', spellUrlPath: '/4795-virility' },
      { spellId: 4797, spellName: 'Authority', spellUrlPath: '/4797-authority' },
      { spellId: 4798, spellName: 'Show Off', spellUrlPath: '/4798-show-off' },
      { spellId: 4799, spellName: 'Locking Pro', spellUrlPath: '/4799-locking-pro' },
      { spellId: 5102, spellName: 'King of the Hill', spellUrlPath: '/5102-king-hill' },
      { spellId: 4796, spellName: 'Compulsion', spellUrlPath: '/4796-compulsion' },
      { spellId: 5101, spellName: 'Furious Charge', spellUrlPath: '/5101-furious-charge' },
      { spellId: 5104, spellName: 'Seismic Rift', spellUrlPath: '/5104-seismic-rift' },
      { spellId: 5100, spellName: 'Bravery', spellUrlPath: '/5100-bravery' },
      { spellId: 5103, spellName: 'Tormentor', spellUrlPath: '/5103-tormentor' },
    ],
  },
  {
    classUrlPath: '/9-cra',
    className: 'Cra',
    classId: 9,
    spells: [
      { spellId: 4805, spellName: 'Beacon Sneakin', spellUrlPath: '/4805-beacon-sneakin' },
      { spellId: 4806, spellName: 'Scout', spellUrlPath: '/4806-scout' },
      { spellId: 7753, spellName: 'Bats Eye', spellUrlPath: '/7753-bat-eye' },
      { spellId: 4808, spellName: 'Biting Blow', spellUrlPath: '/4808-biting-blow' },
      { spellId: 6842, spellName: 'Flurry', spellUrlPath: '/6842-flurry' },
      { spellId: 4774, spellName: 'Roly Poly', spellUrlPath: '/4774-roly-poly' },
      { spellId: 6945, spellName: 'Devious Archer', spellUrlPath: '/6945-devious-archer' },
      { spellId: 6956, spellName: 'Untouchable Scout', spellUrlPath: '/6956-untouchable-scout' },
      { spellId: 6963, spellName: 'Cra Perforation', spellUrlPath: '/6963-cra-perforation' },
      { spellId: 7795, spellName: 'Protective Point', spellUrlPath: '/7795-protective-point' },
      { spellId: 6961, spellName: 'The Art of Beacons', spellUrlPath: '/6961-art-beacons' },
      { spellId: 6949, spellName: 'Focal Distance', spellUrlPath: '/6949-focal-distance' },
      { spellId: 6948, spellName: 'Firm Stance', spellUrlPath: '/6948-firm-stance' },
      { spellId: 6958, spellName: 'Short Range Beaconing', spellUrlPath: '/6958-short-range-beaconing' },
      { spellId: 6959, spellName: 'Lone Shooter', spellUrlPath: '/6959-lone-shooter' },
      { spellId: 6951, spellName: 'The Way of the Bow', spellUrlPath: '/6951-way-bow' },
      { spellId: 6955, spellName: 'Cras Paradox', spellUrlPath: '/6955-cra-paradox' },
      { spellId: 6953, spellName: 'Brutal Redirection', spellUrlPath: '/6953-brutal-redirection' },
      { spellId: 6952, spellName: 'Massive Beagon', spellUrlPath: '/6952-massive-beagon' },
      { spellId: 6957, spellName: 'Hunters Instinct', spellUrlPath: '/6957-hunter-instinct' },
      { spellId: 6960, spellName: 'Sharp Mind', spellUrlPath: '/6960-sharp-mind' },
      { spellId: 6950, spellName: 'Voracious Precision', spellUrlPath: '/6950-voracious-precision' },
      { spellId: 6947, spellName: 'Discreet Beacons', spellUrlPath: '/6947-discreet-beacons' },
      { spellId: 6946, spellName: 'Scout Specialty', spellUrlPath: '/6946-scout-specialty' },
      { spellId: 6962, spellName: 'Timely Movement', spellUrlPath: '/6962-timely-movement' },
    ],
  },
  {
    classUrlPath: '/10-sadida',
    className: 'Sadida',
    classId: 10,
    spells: [
      { spellId: 911, spellName: 'The Ultra Powerful', spellUrlPath: '/911-ultra-powerful' },
      { spellId: 920, spellName: 'Dolly Sacrifice', spellUrlPath: '/920-dolly-sacrifice' },
      { spellId: 915, spellName: 'Tree', spellUrlPath: '/915-tree' },
      { spellId: 926, spellName: 'The Voodoll', spellUrlPath: '/926-voodoll' },
      { spellId: 5057, spellName: 'Sylvan Awakening', spellUrlPath: '/5057-sylvan-awakening' },
      { spellId: 914, spellName: 'Sic Em More', spellUrlPath: '/914-sic-em-more' },
      { spellId: 917, spellName: 'Knowledge of Dolls', spellUrlPath: '/917-knowledge-dolls' },
      { spellId: 4959, spellName: 'Sadida Prayer', spellUrlPath: '/4959-sadida-prayer' },
      { spellId: 916, spellName: 'Doll Link', spellUrlPath: '/916-doll-link' },
      { spellId: 913, spellName: 'Green Guard', spellUrlPath: '/913-green-guard' },
      { spellId: 933, spellName: 'Explodoll', spellUrlPath: '/933-explodoll' },
      { spellId: 5055, spellName: 'Harmless Toxin', spellUrlPath: '/5055-harmless-toxin' },
      { spellId: 912, spellName: 'Lone Sadida', spellUrlPath: '/912-lone-sadida' },
      { spellId: 5058, spellName: 'Wild Whispers', spellUrlPath: '/5058-wild-whispers' },
      { spellId: 5234, spellName: 'Venomous', spellUrlPath: '/5234-venomous' },
      { spellId: 7053, spellName: 'Common Ground', spellUrlPath: '/7053-common-ground' },
    ],
  },
  {
    classUrlPath: '/11-sacrieur',
    className: 'Sacrieur',
    classId: 11,
    spells: [
      { spellId: 5043, spellName: 'Attraction', spellUrlPath: '/5043-attraction' },
      { spellId: 5045, spellName: 'Sacrifice', spellUrlPath: '/5045-sacrifice' },
      { spellId: 5044, spellName: 'Transposition', spellUrlPath: '/5044-transposition' },
      { spellId: 5047, spellName: 'Sanguine Armor', spellUrlPath: '/5047-sanguine-armor' },
      { spellId: 7211, spellName: 'Gash', spellUrlPath: '/7211-gash' },
      { spellId: 7212, spellName: 'Blood Transfer', spellUrlPath: '/7212-blood-transfer' },
      { spellId: 7213, spellName: 'Blood Flow', spellUrlPath: '/7213-blood-flow' },
      { spellId: 7224, spellName: 'Burning', spellUrlPath: '/7224-burning' },
      { spellId: 7220, spellName: 'Pillar', spellUrlPath: '/7220-pillar' },
      { spellId: 7219, spellName: 'Motion Sick', spellUrlPath: '/7219-motion-sick' },
      { spellId: 7218, spellName: 'Sacriers Heart', spellUrlPath: '/7218-sacrier-heart' },
      { spellId: 7217, spellName: 'Wakfu Pact', spellUrlPath: '/7217-wakfu-pact' },
      { spellId: 7216, spellName: 'Burning Armor', spellUrlPath: '/7216-burning-armor' },
      { spellId: 7215, spellName: 'Vision', spellUrlPath: '/7215-vision' },
      { spellId: 7214, spellName: 'Dangerous Game', spellUrlPath: '/7214-dangerous-game' },
      { spellId: 5049, spellName: 'Blood Trail', spellUrlPath: '/5049-blood-trail' },
      { spellId: 5052, spellName: 'Clinging to Life', spellUrlPath: '/5052-clinging-life' },
      { spellId: 5195, spellName: 'Smasher', spellUrlPath: '/5195-smasher' },
      { spellId: 5050, spellName: 'Placidity', spellUrlPath: '/5050-placidity' },
      { spellId: 5054, spellName: 'Transcendence', spellUrlPath: '/5054-transcendence' },
      { spellId: 5193, spellName: 'Libation', spellUrlPath: '/5193-libation' },
      { spellId: 5053, spellName: 'Blood Pact', spellUrlPath: '/5053-blood-pact' },
      { spellId: 5192, spellName: 'Mobility', spellUrlPath: '/5192-mobility' },
      { spellId: 5194, spellName: 'Wakfu Veins', spellUrlPath: '/5194-wakfu-veins' },
      { spellId: 5051, spellName: 'Tattooed Blood', spellUrlPath: '/5051-tattooed-blood' },
      { spellId: 7830, spellName: 'Executor', spellUrlPath: '/7830-executor' },
    ],
  },
  {
    classUrlPath: '/12-pandawa',
    className: 'Pandawa',
    classId: 12,
    spells: [
      { spellId: 4718, spellName: 'Barrel', spellUrlPath: '/4718-barrel' },
      { spellId: 6844, spellName: 'Thirst', spellUrlPath: '/6844-thirst' },
      { spellId: 4721, spellName: 'Bamboozle', spellUrlPath: '/4721-bamboozle' },
      { spellId: 4719, spellName: 'Ether', spellUrlPath: '/4719-ether' },
      { spellId: 4720, spellName: 'Barrelhop', spellUrlPath: '/4720-barrelhop' },
      { spellId: 6845, spellName: 'Exhilaration', spellUrlPath: '/6845-exhilaration' },
      { spellId: 4722, spellName: 'Cocktail', spellUrlPath: '/4722-cocktail' },
      { spellId: 4723, spellName: 'Master of Merriment', spellUrlPath: '/4723-master-merriment' },
      { spellId: 4724, spellName: 'Bottomless Barrel', spellUrlPath: '/4724-bottomless-barrel' },
      { spellId: 4725, spellName: 'Aggressive Barrel', spellUrlPath: '/4725-aggressive-barrel' },
      { spellId: 4726, spellName: 'Milky Instinct', spellUrlPath: '/4726-milky-instinct' },
      { spellId: 5148, spellName: 'Bambottle', spellUrlPath: '/5148-bambottle' },
      { spellId: 5149, spellName: 'Poisoned Chalice', spellUrlPath: '/5149-poisoned-chalice' },
      { spellId: 5150, spellName: 'Refreshment', spellUrlPath: '/5150-refreshment' },
      { spellId: 5151, spellName: 'Pandemic', spellUrlPath: '/5151-pandemic' },
      { spellId: 6846, spellName: 'Buzzed', spellUrlPath: '/6846-buzzed' },
    ],
  },
  {
    classUrlPath: '/13-rogue',
    className: 'Rogue',
    classId: 13,
    spells: [
      { spellId: 6494, spellName: 'Smoke Bombs', spellUrlPath: '/6494-smoke-bombs' },
      { spellId: 6492, spellName: 'Claw', spellUrlPath: '/6492-claw' },
      { spellId: 6491, spellName: 'Evanescence', spellUrlPath: '/6491-evanescence' },
      { spellId: 6493, spellName: 'Magnet', spellUrlPath: '/6493-magnet' },
      { spellId: 6489, spellName: 'Fusillade', spellUrlPath: '/6489-fusillade' },
      { spellId: 6490, spellName: 'Boot', spellUrlPath: '/6490-boot' },
      { spellId: 7983, spellName: 'Powder Trail', spellUrlPath: '/7983-powder-trail' },
      { spellId: 7091, spellName: 'Rogue Master', spellUrlPath: '/7091-rogue-master' },
      { spellId: 7982, spellName: 'Tactician', spellUrlPath: '/7982-tactician' },
      { spellId: 7092, spellName: 'Jackpot', spellUrlPath: '/7092-jackpot' },
      { spellId: 7064, spellName: 'Dynamite', spellUrlPath: '/7064-dynamite' },
      { spellId: 6487, spellName: 'Powder Wall', spellUrlPath: '/6487-powder-wall' },
      { spellId: 6484, spellName: 'Minesweeper', spellUrlPath: '/6484-minesweeper' },
      { spellId: 6485, spellName: 'Rusty Blade', spellUrlPath: '/6485-rusty-blade' },
      { spellId: 7063, spellName: 'Powder Keg', spellUrlPath: '/7063-powder-keg' },
      { spellId: 6483, spellName: 'Reinforced Tunic', spellUrlPath: '/6483-reinforced-tunic' },
      { spellId: 6480, spellName: 'Escapist', spellUrlPath: '/6480-escapist' },
      { spellId: 7062, spellName: 'Surprise Shot', spellUrlPath: '/7062-surprise-shot' },
      { spellId: 6481, spellName: 'Bomber Fan', spellUrlPath: '/6481-bomber-fan' },
      { spellId: 7090, spellName: 'Elemental Bombs', spellUrlPath: '/7090-elemental-bombs' },
      { spellId: 6486, spellName: 'Blade Master', spellUrlPath: '/6486-blade-master' },
      { spellId: 6488, spellName: 'Fugitive', spellUrlPath: '/6488-fugitive' },
      { spellId: 6482, spellName: 'Pyrotechnist', spellUrlPath: '/6482-pyrotechnist' },
      { spellId: 7065, spellName: 'Explobomb', spellUrlPath: '/7065-explobomb' },
      { spellId: 6479, spellName: 'Boomarogue', spellUrlPath: '/6479-boomarogue' },
      { spellId: 7984, spellName: 'Time Bombs', spellUrlPath: '/7984-time-bombs' },
    ],
  },
  {
    classUrlPath: '/14-masqueraider',
    className: 'Masqueraider',
    classId: 14,
    spells: [
      { spellId: 7084, spellName: 'Masked Spirit', spellUrlPath: '/7084-masked-spirit' },
      { spellId: 7085, spellName: 'Inspiring Dance', spellUrlPath: '/7085-inspiring-dance' },
      { spellId: 7086, spellName: 'Dance of Death', spellUrlPath: '/7086-dance-death' },
      { spellId: 7087, spellName: 'Acrobatics', spellUrlPath: '/7087-acrobatics' },
      { spellId: 7088, spellName: 'Brutality Aura', spellUrlPath: '/7088-brutality-aura' },
      { spellId: 7089, spellName: 'Solidity', spellUrlPath: '/7089-solidity' },
      { spellId: 7103, spellName: 'Support Collisions', spellUrlPath: '/7103-support-collisions' },
      { spellId: 7112, spellName: 'Masked Gaze', spellUrlPath: '/7112-masked-gaze' },
      { spellId: 7111, spellName: 'Artful Dodger', spellUrlPath: '/7111-artful-dodger' },
      { spellId: 7108, spellName: 'Keep in Contact', spellUrlPath: '/7108-keep-contact' },
      { spellId: 7107, spellName: 'Mirrors', spellUrlPath: '/7107-mirrors' },
      { spellId: 7106, spellName: 'Regenerating Collisions', spellUrlPath: '/7106-regenerating-collisions' },
      { spellId: 7105, spellName: 'Pirouette', spellUrlPath: '/7105-pirouette' },
      { spellId: 7104, spellName: 'Erosion', spellUrlPath: '/7104-erosion' },
      { spellId: 7099, spellName: 'Unique Armor', spellUrlPath: '/7099-unique-armor' },
      { spellId: 7102, spellName: 'Cautious Protector', spellUrlPath: '/7102-cautious-protector' },
      { spellId: 7101, spellName: 'Brute', spellUrlPath: '/7101-brute' },
      { spellId: 7100, spellName: 'Anchor', spellUrlPath: '/7100-anchor' },
      { spellId: 7093, spellName: 'Fancy Footwork', spellUrlPath: '/7093-fancy-footwork' },
      { spellId: 7098, spellName: 'Carnival', spellUrlPath: '/7098-carnival' },
      { spellId: 7097, spellName: 'Health Mask', spellUrlPath: '/7097-health-mask' },
      { spellId: 7096, spellName: 'Artful Locker', spellUrlPath: '/7096-artful-locker' },
      { spellId: 7095, spellName: 'Violent Pushes', spellUrlPath: '/7095-violent-pushes' },
      { spellId: 7094, spellName: 'Masks Off', spellUrlPath: '/7094-masks-off' },
      { spellId: 7113, spellName: 'Debuff Pushes', spellUrlPath: '/7113-debuff-pushes' },
    ],
  },
  {
    classUrlPath: '/15-ouginak',
    className: 'Ouginak',
    classId: 15,
    spells: [
      { spellId: 6284, spellName: 'Hunter', spellUrlPath: '/6284-hunter' },
      { spellId: 6287, spellName: 'Canine', spellUrlPath: '/6287-canine' },
      { spellId: 6288, spellName: 'Appeasement', spellUrlPath: '/6288-appeasement' },
      { spellId: 6285, spellName: 'Pursuit', spellUrlPath: '/6285-pursuit' },
      { spellId: 7551, spellName: 'Pack', spellUrlPath: '/7551-pack' },
      { spellId: 7552, spellName: 'Surge', spellUrlPath: '/7552-surge' },
      { spellId: 6276, spellName: 'Exhaustion', spellUrlPath: '/6276-exhaustion' },
      { spellId: 6282, spellName: 'Wise Strength', spellUrlPath: '/6282-wise-strength' },
      { spellId: 7558, spellName: 'Canine Tracker', spellUrlPath: '/7558-canine-tracker' },
      { spellId: 6278, spellName: 'Cunning Fang', spellUrlPath: '/6278-cunning-fang' },
      { spellId: 6271, spellName: 'Burrow', spellUrlPath: '/6271-burrow' },
      { spellId: 6272, spellName: 'Canine Art', spellUrlPath: '/6272-canine-art' },
      { spellId: 6279, spellName: 'Sniff', spellUrlPath: '/6279-sniff' },
      { spellId: 6281, spellName: 'Tailing', spellUrlPath: '/6281-tailing' },
      { spellId: 7556, spellName: 'Canine Energy', spellUrlPath: '/7556-canine-energy' },
      { spellId: 7557, spellName: 'Fury', spellUrlPath: '/7557-fury' },
      { spellId: 6277, spellName: 'Raiding', spellUrlPath: '/6277-raiding' },
      { spellId: 6275, spellName: 'Ardor', spellUrlPath: '/6275-ardor' },
      { spellId: 7555, spellName: 'Digestion', spellUrlPath: '/7555-digestion' },
      { spellId: 7554, spellName: 'Open Season', spellUrlPath: '/7554-open-season' },
      { spellId: 7553, spellName: 'Relentless', spellUrlPath: '/7553-relentless' },
      { spellId: 7596, spellName: 'Growlight', spellUrlPath: '/7596-growlight' },
      { spellId: 6280, spellName: 'Haggling', spellUrlPath: '/6280-haggling' },
      { spellId: 6274, spellName: 'Sidekick', spellUrlPath: '/6274-sidekick' },
      { spellId: 6273, spellName: 'Dog Handler', spellUrlPath: '/6273-dog-handler' },
    ],
  },
  {
    classUrlPath: '/16-foggernaut',
    className: 'Foggernaut',
    classId: 16,
    spells: [
      { spellId: 6917, spellName: 'Armor Plating', spellUrlPath: '/6917-armor-plating' },
      { spellId: 6918, spellName: 'Hypertension', spellUrlPath: '/6918-hypertension' },
      { spellId: 6919, spellName: 'Machinery', spellUrlPath: '/6919-machinery' },
      { spellId: 6920, spellName: 'Ambush', spellUrlPath: '/6920-ambush' },
      { spellId: 6921, spellName: 'Transition', spellUrlPath: '/6921-transition' },
      { spellId: 6922, spellName: 'Stasis Flux', spellUrlPath: '/6922-stasis-flux' },
      { spellId: 6935, spellName: 'Brutal Transfer', spellUrlPath: '/6935-brutal-transfer' },
      { spellId: 6943, spellName: 'Advanced Mechanics', spellUrlPath: '/6943-advanced-mechanics' },
      { spellId: 6942, spellName: 'Tactician', spellUrlPath: '/6942-tactician' },
      { spellId: 6941, spellName: 'Serene Conquest', spellUrlPath: '/6941-serene-conquest' },
      { spellId: 6940, spellName: 'Hot Wheels', spellUrlPath: '/6940-hot-wheels' },
      { spellId: 6939, spellName: 'Stasified Protection', spellUrlPath: '/6939-stasified-protection' },
      { spellId: 6938, spellName: 'Immediate Execution', spellUrlPath: '/6938-immediate-execution' },
      { spellId: 6937, spellName: 'Activation', spellUrlPath: '/6937-activation' },
      { spellId: 6936, spellName: 'Heavy Duty Covering', spellUrlPath: '/6936-heavy-duty-covering' },
      { spellId: 6932, spellName: 'Mechanical Substitution', spellUrlPath: '/6932-mechanical-substitution' },
      { spellId: 6934, spellName: 'Light Alloy', spellUrlPath: '/6934-light-alloy' },
      { spellId: 6933, spellName: 'Patience', spellUrlPath: '/6933-patience' },
      { spellId: 6925, spellName: 'Energy Moderator', spellUrlPath: '/6925-energy-moderator' },
      { spellId: 6931, spellName: 'Earthy Assistance', spellUrlPath: '/6931-earthy-assistance' },
      { spellId: 6930, spellName: 'Transportation Technology', spellUrlPath: '/6930-transportation-technology' },
      { spellId: 6929, spellName: 'Robotic Strategy', spellUrlPath: '/6929-robotic-strategy' },
      { spellId: 6928, spellName: 'Reinforced Armor Plating', spellUrlPath: '/6928-reinforced-armor-plating' },
      { spellId: 6927, spellName: 'Versatility', spellUrlPath: '/6927-versatility' },
      { spellId: 6926, spellName: 'Winding Roads', spellUrlPath: '/6926-winding-roads' },
      { spellId: 7810, spellName: 'Switching', spellUrlPath: '/7810-switching' },
    ],
  },
  {
    classUrlPath: '/18-eliotrope',
    className: 'Eliotrope',
    classId: 18,
    spells: [
      { spellId: 7199, spellName: 'Coalition', spellUrlPath: '/7199-coalition' },
      { spellId: 7198, spellName: 'Wakfu Imprint', spellUrlPath: '/7198-wakfu-imprint' },
      { spellId: 4683, spellName: 'Time Breach', spellUrlPath: '/4683-time-breach' },
      { spellId: 4684, spellName: 'Exodus', spellUrlPath: '/4684-exodus' },
      { spellId: 4685, spellName: 'Incandescence', spellUrlPath: '/4685-incandescence' },
      { spellId: 7200, spellName: 'Barrier', spellUrlPath: '/7200-barrier' },
      { spellId: 7203, spellName: 'White Dimension', spellUrlPath: '/7203-white-dimension' },
      { spellId: 7720, spellName: 'Lunar System', spellUrlPath: '/7720-lunar-system' },
      { spellId: 7210, spellName: 'Concentration', spellUrlPath: '/7210-concentration' },
      { spellId: 7209, spellName: 'Healing', spellUrlPath: '/7209-healing' },
      { spellId: 7208, spellName: 'Novice Sword', spellUrlPath: '/7208-novice-sword' },
      { spellId: 7207, spellName: 'Final Shield', spellUrlPath: '/7207-final-shield' },
      { spellId: 7206, spellName: 'Portail', spellUrlPath: '/7206-porta-i' },
      { spellId: 7205, spellName: 'Spacetime', spellUrlPath: '/7205-spacetime' },
      { spellId: 7204, spellName: 'Quietude', spellUrlPath: '/7204-quietude' },
      { spellId: 5056, spellName: 'Portal Disciple', spellUrlPath: '/5056-portal-disciple' },
      { spellId: 7202, spellName: 'Interstellar', spellUrlPath: '/7202-interstellar' },
      { spellId: 5132, spellName: 'Reminiscence', spellUrlPath: '/5132-reminiscence' },
      { spellId: 4690, spellName: 'Resilience', spellUrlPath: '/4690-resilience' },
      { spellId: 5143, spellName: 'Celestial Portal', spellUrlPath: '/5143-celestial-portal' },
      { spellId: 4688, spellName: 'Effervescence', spellUrlPath: '/4688-effervescence' },
      { spellId: 5131, spellName: 'Transitory', spellUrlPath: '/5131-transitory' },
      { spellId: 4686, spellName: 'Fury', spellUrlPath: '/4686-fury' },
      { spellId: 4689, spellName: 'Medium', spellUrlPath: '/4689-medium' },
      { spellId: 4687, spellName: 'Trapster', spellUrlPath: '/4687-trapster' },
      { spellId: 7814, spellName: 'Breath of the Goddess', spellUrlPath: '/7814-breath-goddess' },
    ],
  },
  {
    classUrlPath: '/19-huppermage',
    className: 'Huppermage',
    classId: 19,
    spells: [
      { spellId: 5575, spellName: 'Solar Stronghold', spellUrlPath: '/5575-solar-stronghold' },
      { spellId: 7755, spellName: 'Runic Overcharge', spellUrlPath: '/7755-runic-overcharge' },
      { spellId: 5576, spellName: 'Wall of Energy', spellUrlPath: '/5576-wall-energy' },
      { spellId: 7754, spellName: 'Visio Imperum', spellUrlPath: '/7754-visio-imperum' },
      { spellId: 5577, spellName: 'Principio Valere', spellUrlPath: '/5577-principio-valere' },
      { spellId: 7809, spellName: 'Runification', spellUrlPath: '/7809-runification' },
      { spellId: 5588, spellName: 'Elemental Refraction', spellUrlPath: '/5588-elemental-refraction' },
      { spellId: 7800, spellName: 'Elemental Combination', spellUrlPath: '/7800-elemental-combination' },
      { spellId: 5580, spellName: 'Soul Initiative', spellUrlPath: '/5580-soul-initiative' },
      { spellId: 5584, spellName: 'Runic Save', spellUrlPath: '/5584-runic-save' },
      { spellId: 7801, spellName: 'Pulsation', spellUrlPath: '/7801-pulsation' },
      { spellId: 7803, spellName: 'Soul Development', spellUrlPath: '/7803-soul-development' },
      { spellId: 7805, spellName: 'New Breath', spellUrlPath: '/7805-new-breath' },
      { spellId: 7804, spellName: 'Soul Altruism', spellUrlPath: '/7804-soul-altruism' },
      { spellId: 7797, spellName: 'Sensextension', spellUrlPath: '/7797-sensextension' },
      { spellId: 5587, spellName: 'Quadramental Absorption', spellUrlPath: '/5587-quadramental-absorption' },
      { spellId: 5586, spellName: 'Runic Profusion', spellUrlPath: '/5586-runic-profusion' },
      { spellId: 5579, spellName: 'Dynamo', spellUrlPath: '/5579-dynamo' },
      { spellId: 5583, spellName: 'Universality', spellUrlPath: '/5583-universality' },
      { spellId: 5585, spellName: 'Fullness', spellUrlPath: '/5585-fullness' },
      { spellId: 5582, spellName: 'Light Link', spellUrlPath: '/5582-light-link' },
      { spellId: 5581, spellName: 'Elemental Distension', spellUrlPath: '/5581-elemental-distension' },
      { spellId: 7802, spellName: 'Antithesis', spellUrlPath: '/7802-antithesis' },
      { spellId: 7798, spellName: 'Runic Transcendence', spellUrlPath: '/7798-runic-transcendence' },
    ],
  },
];

  // {
  //   classUrlPath: '/path',
  //   className: 'name',
  //   classId: 11111,
  //   spells: [
  //     { spellId: 15125125125125, spellName: 'name', spellUrlPath: '/path' },
  //   ],
  // },

const fs = require('fs');

const getHtmlData = async () => {
  for (let classIndex in classEncyclopediaBreakdown) {
    let classEntry = classEncyclopediaBreakdown[classIndex];
    let targetClassDirectory = 'spellData/' + classEntry.className.toLowerCase() + '/';

    // first we make any missing directories. we assume the /spellData directory already exists.
    if(!fs.existsSync(targetClassDirectory)) {
      fs.mkdir(targetClassDirectory, (error) => {
        if (error) {
          console.log(error);
        }
      });
    }

    // next we iterate over the spells
    for (let spellIndex in classEntry.spells) {
      let spellEntry = classEntry.spells[spellIndex];
      let targetHtmlUrl = baseUrl + classEntry.classUrlPath + spellEntry.spellUrlPath + urlParams;
      let targetFilePath = targetClassDirectory + spellEntry.spellName.toLowerCase().replaceAll(' ', '_') + '.html';
      console.log(targetFilePath);

      let fileExists = await fs.existsSync(targetFilePath);
      if(process.argv.includes('skip-existing') && fileExists) {
        continue;
      }

      let response = await fetch(targetHtmlUrl, {
        "headers": {
          "x-pjax": "true",
          "x-pjax-container": ".ak-spells-panel",
          "x-requested-with": "XMLHttpRequest"
        },
      });

      let htmlText = await response.text();

      await fs.writeFile(targetFilePath, htmlText, () => {});

      await new Promise((resolve) => setTimeout(resolve, 250));
    };
  }
};

getHtmlData();